sudo: required
services:   
    -docker

before_install:
    - docker build -t ashpalsin/react-test -f ./client/Dockerfile.dev ./client
    
    
script:
    - docker run ashpalsin/react-test npm test -- --coverage
    
after_success:
    - docker build -t ashpalsin/multi-client ./client
    - docker build -t ashpalsin/multi-nginx ./nginx
    - docker build -t ashpalsin/multi-server ./server
    - docker build -t ashpalsin/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ashpalsin/multi-client
    - docker push ashpalsin/multi-nginx
    - docker push ashpalsin/multi-server
    - docker push ashpalsin/multi-worker